name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Add
        id: add
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Add
          setup-command: ''
          command: './mvnw test -Dtest=AddTest'
          timeout: 1
          max-score: 1

      - name: Average
        id: average
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Average
          setup-command: ''
          command: './mvnw test -Dtest=AverageTest'
          timeout: 1
          max-score: 1

      - name: Divide
        id: divide
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Divide
          setup-command: ''
          command: './mvnw test -Dtest=DivideTest'
          timeout: 1
          max-score: 1

      - name: GCD
        id: gcd
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: GCD
          setup-command: ''
          command: './mvnw test -Dtest=GcdTest'
          timeout: 1
          max-score: 1

      - name: Heron
        id: heron
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Heron
          setup-command: ''
          command: './mvnw test -Dtest=HeronTest'
          timeout: 1
          max-score: 1

      - name: MaxOfThree
        id: maxofthree
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: MaxOfThree
          setup-command: ''
          command: './mvnw test -Dtest=MaxOfThreeTest'
          timeout: 1
          max-score: 1

      - name: Multiply
        id: multiply
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Multiply
          setup-command: ''
          command: './mvnw test -Dtest=MultiplyTest'
          timeout: 1
          max-score: 1

      - name: Power
        id: power
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Power
          setup-command: ''
          command: './mvnw test -Dtest=PowerTest'
          timeout: 1
          max-score: 1

      - name: Remainder
        id: remainder
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Remainder
          setup-command: ''
          command: './mvnw test -Dtest=RemainderTest'
          timeout: 1
          max-score: 1

      - name: Subtract
        id: subtract
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: Subtract
          setup-command: ''
          command: './mvnw test -Dtest=SubtractTest'
          timeout: 1
          max-score: 1

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          ADD_RESULTS: '${{steps.add.outputs.result}}'
          AVERAGE_RESULTS: '${{steps.average.outputs.result}}'
          DIVIDE_RESULTS: '${{steps.divide.outputs.result}}'
          GCD_RESULTS: '${{steps.gcd.outputs.result}}'
          HERON_RESULTS: '${{steps.heron.outputs.result}}'
          MAXOFTHREE_RESULTS: '${{steps.maxofthree.outputs.result}}'
          MULTIPLY_RESULTS: '${{steps.multiply.outputs.result}}'
          POWER_RESULTS: '${{steps.power.outputs.result}}'
          REMAINDER_RESULTS: '${{steps.remainder.outputs.result}}'
          SUBTRACT_RESULTS: '${{steps.subtract.outputs.result}}'
        with:
          runners: add,average,divide,gcd,heron,maxofthree,multiply,power,remainder,subtract
